# Generated by Django 4.2.17 on 2024-12-19 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('sId', models.AutoField(primary_key=True, serialize=False)),
                ('sName', models.CharField(max_length=100)),
                ('sbrand', models.CharField(max_length=100)),
                ('size', models.IntegerField()),
                ('stype', models.CharField(max_length=100)),
                ('price', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('Men', 'men'), ('Women', 'women'), ('Girls', 'girls'), ('Boys', 'boys')], default='active', max_length=10)),
            ],
        ),
    ]
