# Generated by Django 4.2.17 on 2024-12-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('foodId', models.AutoField(primary_key=True, serialize=False)),
                ('foodName', models.CharField(max_length=100)),
                ('foodType', models.CharField(max_length=100)),
                ('foodCategory', models.CharField(max_length=100)),
                ('foodPrice', models.FloatField(default=0.0)),
            ],
        ),
    ]
